
package View;

import Controller.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Model.*;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.*;

/**
 *
 * @author rohan-manandhar
 */
public class AdminDashboard extends javax.swing.JFrame {
    DefaultTableModel dtm;
    AdminCdeleteModel model;
    AdminCreateCustomerModel Model ;
    AdminCreateSupModel initModel;
    AdminUpdateProductModel initModel1;
    private AdminCreateCustomerController Accc;
    private adminCdeleteController D1;
    private AdminCreateSupController initCont;
    private AdminUpdateProductController initCont1;
            
    /**
     * Creates new form adminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    // sending data to model
    
    // cusDeleteID
    public AdminCdeleteModel getUser(){
        model = new AdminCdeleteModel(txtCdeleteid.getText());
        return model;
    }
    
    // cusModel
    public AdminCreateCustomerModel getCUser()
    {     
        String username = txtCusername.getText();
        String fname = txtCfname.getText();
        String lname = txtClname.getText();
        String email = txtCemail.getText();
        String phone = txtCphone.getText();
        String password = txtCpassword.getText();

        Model = new AdminCreateCustomerModel(username, fname, lname, email, phone, password);
        return Model;
    }
    
    // supModel
    public AdminCreateSupModel getSupUSer(){
        String username = txtSusername.getText();
        String companyname = txtcompanyname.getText();
        String email = txtSemail.getText();
        String phone = txtSphone.getText();
        String password = txtSpassword.getText();
        
        initModel = new AdminCreateSupModel(username, companyname, email, phone, password);
        return initModel;
    }
    
    // prodModel
    public AdminUpdateProductModel getProductdata(){
        int pid = Integer.parseInt(txtpid.getText());
        String productName = txtproductname.getText();
        double productPrice = Double.parseDouble(txtproductprice.getText());
        
        initModel1 = new AdminUpdateProductModel(pid, productName, productPrice);
        return initModel1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();
        txtCusername = new javax.swing.JTextField();
        btnCview = new javax.swing.JButton();
        txtCfname = new javax.swing.JTextField();
        txtCemail = new javax.swing.JTextField();
        txtCpassword = new javax.swing.JTextField();
        txtCphone = new javax.swing.JTextField();
        txtClname = new javax.swing.JTextField();
        btnCcreate = new javax.swing.JButton();
        txtCdeleteid = new javax.swing.JTextField();
        btnCdelete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        suppliertable = new javax.swing.JTable();
        txtSusername = new javax.swing.JTextField();
        btnSview = new javax.swing.JButton();
        txtcompanyname = new javax.swing.JTextField();
        txtSemail = new javax.swing.JTextField();
        txtSpassword = new javax.swing.JTextField();
        txtSphone = new javax.swing.JTextField();
        btnScreate = new javax.swing.JButton();
        btnSdelete = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        txtpid = new javax.swing.JTextField();
        btnPview = new javax.swing.JButton();
        txtproductname = new javax.swing.JTextField();
        txtproductprice = new javax.swing.JTextField();
        btnPupdate = new javax.swing.JButton();
        btnPdelteid = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("adminframe"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel2.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel2.setText("WELCOME TO ADMIN DASHBOARD");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(140, 100, 29));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to admin profile");

        jLabel3.setText("Image");

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel4.setText(": admin");

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel5.setText(": world");

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel6.setText("Admin username");

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel7.setText("Admin Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(88, 88, 88))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Admin info", jPanel4);

        jPanel5.setBackground(new java.awt.Color(140, 100, 29));

        customertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        customertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "fname", "lname", "email", "phone", "password"
            }
        ));
        customertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(customertable);

        txtCusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCusernameFocusLost(evt);
            }
        });

        btnCview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnCview.setText("View user");
        btnCview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCviewActionPerformed(evt);
            }
        });

        txtCfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCfnameFocusLost(evt);
            }
        });

        txtCemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCemailFocusLost(evt);
            }
        });

        txtCpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpasswordFocusLost(evt);
            }
        });

        txtCphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCphoneFocusLost(evt);
            }
        });

        txtClname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClnameFocusLost(evt);
            }
        });

        btnCcreate.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnCcreate.setText("Create user");
        btnCcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCcreateActionPerformed(evt);
            }
        });

        txtCdeleteid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCdeleteidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCdeleteidFocusLost(evt);
            }
        });

        btnCdelete.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnCdelete.setText("Delete user");
        btnCdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCdeleteid, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(btnCview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCcreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCemail, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCfname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCusername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCphone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCview, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCdeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Customer", jPanel5);

        jPanel6.setBackground(new java.awt.Color(140, 100, 29));

        suppliertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        suppliertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Company Name", "Email", "Phone", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        suppliertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(suppliertable);

        txtSusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSusernameFocusLost(evt);
            }
        });

        btnSview.setBackground(new java.awt.Color(0, 153, 204));
        btnSview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnSview.setText("View user");
        btnSview.setBorder(null);
        btnSview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSviewActionPerformed(evt);
            }
        });

        txtcompanyname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcompanynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcompanynameFocusLost(evt);
            }
        });

        txtSemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSemailFocusLost(evt);
            }
        });

        txtSpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSpasswordFocusLost(evt);
            }
        });

        txtSphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSphoneFocusLost(evt);
            }
        });

        btnScreate.setBackground(new java.awt.Color(0, 153, 204));
        btnScreate.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnScreate.setText("Create user");
        btnScreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScreateActionPerformed(evt);
            }
        });

        btnSdelete.setText("Delete user");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScreate, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(btnSdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSemail, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtcompanyname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSusername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSphone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnScreate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSview, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtSusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Supplier", jPanel6);

        jPanel8.setBackground(new java.awt.Color(140, 100, 29));

        producttable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product name", "Product price", "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        producttable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(producttable);

        txtpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpidFocusLost(evt);
            }
        });

        btnPview.setBackground(new java.awt.Color(0, 153, 204));
        btnPview.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnPview.setText("View products");
        btnPview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPviewActionPerformed(evt);
            }
        });

        txtproductname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductnameFocusLost(evt);
            }
        });

        txtproductprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductpriceFocusLost(evt);
            }
        });

        btnPupdate.setBackground(new java.awt.Color(0, 153, 204));
        btnPupdate.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnPupdate.setText("Update product");
        btnPupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPupdateActionPerformed(evt);
            }
        });

        btnPdelteid.setText("Delete user");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPupdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPdelteid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtproductname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtproductprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPview, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPdelteid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproductprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Product", jPanel8);

        btnLogout.setBackground(java.awt.SystemColor.controlDkShadow);
        btnLogout.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnLogout.setText("Boss Log out");
        btnLogout.setBorder(null);
        btnLogout.setOpaque(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Boss thanks for the Hardwork", "Admin logged out",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnCviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCviewActionPerformed
        AdminCdisplay Model = new AdminCdisplay();
        List<AdminCmodel> customerList = Model.getCustomerData();
        
        dtm = (DefaultTableModel)customertable.getModel();
        dtm.setRowCount(0);
        // Iterate over the customer list and access the data
        for (AdminCmodel customer : customerList) {
            
            // getting value from model
            String username = customer.getUsername();
            String fname = customer.getFname();
            String lname = customer.getLname();
            String email = customer.getEmail();
            String phone = customer.getPhone();
            String password = customer.getPassword();

            // creating a object with customer data
            Object[] rowData = {username, fname, lname, email, phone, password};

            // Add the row to the table model
            dtm.addRow((Object[]) rowData);
            System.out.println(username);
        }
            // checking this as alternative 
            //customertable.setModel(dtm);
    }//GEN-LAST:event_btnCviewActionPerformed

    private void btnCdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCdeleteActionPerformed
        if (D1 == null ){
            D1 = new adminCdeleteController(this);
        }
    }//GEN-LAST:event_btnCdeleteActionPerformed

    //setting some style with focusGained and FocusLost
    private void txtCdeleteidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCdeleteidFocusGained
    if (txtCdeleteid.getText().equals("Enter ID")){
            txtCdeleteid.setText("");
            txtCdeleteid.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCdeleteidFocusGained

    private void txtCdeleteidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCdeleteidFocusLost
        if (txtCdeleteid.getText().isEmpty()){
            txtCdeleteid.setText("Enter ID");
            txtCdeleteid.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtCdeleteidFocusLost

    private void txtCfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCfnameFocusGained
        if (txtCfname.getText().equals("First name: ")){
            txtCfname.setText("");
            txtCfname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCfnameFocusGained

    private void txtCfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCfnameFocusLost
        if (txtCfname.getText().equals("")){
            txtCfname.setText("First name: ");
            txtCfname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCfnameFocusLost

    private void txtClnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClnameFocusGained
        if (txtClname.getText().equals("Last Name: ")){
            txtClname.setText("");
            txtClname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtClnameFocusGained

    private void txtClnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClnameFocusLost
        if (txtClname.getText().equals("")){
            txtClname.setText("Last Name: ");
            txtClname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtClnameFocusLost

    private void txtCemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCemailFocusGained
        if (txtCemail.getText().equals("Email: ")){
            txtCemail.setText("");
            txtCemail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCemailFocusGained

    private void txtCemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCemailFocusLost
        if (txtCemail.getText().equals("")){
            txtCemail.setText("Email: ");
            txtCemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCemailFocusLost

    private void txtCphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCphoneFocusGained
        if (txtCphone.getText().equals("Phone number: ")){
            txtCphone.setText("");
            txtCphone.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCphoneFocusGained

    private void txtCphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCphoneFocusLost
    if (txtCphone.getText().equals("")){
            txtCphone.setText("Phone number: ");
            txtCphone.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCphoneFocusLost

    private void txtCpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpasswordFocusGained
    if (txtCpassword.getText().equals("Password: ")){
            txtCpassword.setText("");
            txtCpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCpasswordFocusGained

    private void txtCpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpasswordFocusLost
        if (txtCpassword.getText().equals("")){
                txtCpassword.setText("Password: ");
                txtCpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCpasswordFocusLost

    private void btnCcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCcreateActionPerformed
        if ( Accc == null){
            Accc = new AdminCreateCustomerController(this);
        }
    }//GEN-LAST:event_btnCcreateActionPerformed

    private void btnSviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSviewActionPerformed
        AdminGetSupDataModel model = new AdminGetSupDataModel();
        List<AdminSendSupDataModel> supplierList = model.getSupData();

        dtm = (DefaultTableModel) suppliertable.getModel();
        dtm.setRowCount(0);

        for (AdminSendSupDataModel supplier : supplierList) {
            String username = supplier.getUsername();
            String companyName = supplier.getCompanyname();
            String email = supplier.getEmail();
            String phone = supplier.getPhone();
            String password = supplier.getPassword();

            Object[] rowData = {username, companyName, email, phone, password};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_btnSviewActionPerformed

    private void btnPviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPviewActionPerformed
        AdminGetProdDataModel model = new AdminGetProdDataModel();
        List<AdminSendProdDataModel> productList = model.getProdData();

        dtm = (DefaultTableModel) producttable.getModel();
        dtm.setRowCount(0);

        for (AdminSendProdDataModel product : productList) {
            int pid = product.getPid();
            String productName = product.getProductname();
            double productPrice = product.getProductprice();
            String supplierName = product.getSuppliername();

            Object[] rowData = {pid, productName, productPrice, supplierName};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_btnPviewActionPerformed

    private void txtCusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCusernameFocusGained
        if (txtCusername.getText().equals("Username: ")){
            txtCusername.setText("");
            txtCusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCusernameFocusGained

    private void txtCusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCusernameFocusLost
        if (txtCusername.getText().equals("")){
            txtCusername.setText("Username: ");
            txtCusername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCusernameFocusLost

    private void txtSusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusGained
        if (txtSusername.getText().equals("Username: ")){
            txtSusername.setText("");
            txtSusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSusernameFocusGained

    private void txtSusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusLost
        if (txtSusername.getText().equals("")){
            txtSusername.setText("Username: ");
            txtSusername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSusernameFocusLost

    private void txtcompanynameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcompanynameFocusGained
        if (txtcompanyname.getText().equals("Company name: ")){
            txtcompanyname.setText("");
            txtcompanyname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcompanynameFocusGained

    private void txtcompanynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcompanynameFocusLost
        if (txtcompanyname.getText().equals("")){
            txtcompanyname.setText("Company name: ");
            txtcompanyname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcompanynameFocusLost

    private void txtSemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemailFocusGained
        if (txtSemail.getText().equals("Email: ")){
            txtSemail.setText("");
            txtSemail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSemailFocusGained

    private void txtSemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemailFocusLost
        if (txtSemail.getText().equals("")){
            txtSemail.setText("Email: ");
            txtSemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSemailFocusLost

    private void txtSphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSphoneFocusGained
        if (txtSphone.getText().equals("Phone Number: ")){
            txtSphone.setText("");
            txtSphone.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSphoneFocusGained

    private void txtSphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSphoneFocusLost
        if (txtSphone.getText().equals("")){
            txtSphone.setText("Phone Number: ");
            txtSphone.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSphoneFocusLost

    private void txtSpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSpasswordFocusGained
        if (txtSpassword.getText().equals("Password: ")){
            txtSpassword.setText("");
            txtSpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSpasswordFocusGained

    private void txtSpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSpasswordFocusLost
        if (txtSpassword.getText().equals("")){
            txtSpassword.setText("Password: ");
            txtSpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSpasswordFocusLost

    private void txtpidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusGained
        if (txtpid.getText().equals("Product ID: ")){
            txtpid.setText("");
            txtpid.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtpidFocusGained

    private void txtpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusLost
        if (txtpid.getText().equals("")){
            txtpid.setText("Product ID: ");
            txtpid.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpidFocusLost

    private void txtproductnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusGained
        if (txtproductname.getText().equals("Product name: ")){
            txtproductname.setText("");
            txtproductname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtproductnameFocusGained

    private void txtproductnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusLost
        if (txtproductname.getText().equals("")){
            txtproductname.setText("Product name: ");
            txtproductname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtproductnameFocusLost

    private void txtproductpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductpriceFocusGained
        if (txtproductprice.getText().equals("Product price: ")){
            txtproductprice.setText("");
            txtproductprice.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtproductpriceFocusGained

    private void txtproductpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductpriceFocusLost
        if (txtproductprice.getText().equals("")){
            txtproductprice.setText("Product price: ");
            txtproductprice.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtproductpriceFocusLost

    private void btnScreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScreateActionPerformed
        if( initCont == null ){
            initCont = new AdminCreateSupController(this);
        }
    }//GEN-LAST:event_btnScreateActionPerformed

    private void btnPupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPupdateActionPerformed
        if (initCont1 == null){
            initCont1 = new AdminUpdateProductController(this);
        }
    }//GEN-LAST:event_btnPupdateActionPerformed
    
    // adding Actionlistener for required 
    public void addLoginListner(ActionListener log){
        btnCdelete.addActionListener(log);
    } 
    
    public void addButtonListener(ActionListener log){
        btnCcreate.addActionListener(log); 
    }
    
    public void addCreateSupListener(ActionListener create){
        btnScreate.addActionListener(create);
    }
    
    public void addUpdateProdListerner( ActionListener update){
        btnPupdate.addActionListener(update);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCcreate;
    private javax.swing.JButton btnCdelete;
    private javax.swing.JButton btnCview;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPdelteid;
    private javax.swing.JButton btnPupdate;
    private javax.swing.JButton btnPview;
    private javax.swing.JButton btnScreate;
    private javax.swing.JButton btnSdelete;
    private javax.swing.JButton btnSview;
    private javax.swing.JTable customertable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable producttable;
    private javax.swing.JTable suppliertable;
    private javax.swing.JTextField txtCdeleteid;
    private javax.swing.JTextField txtCemail;
    private javax.swing.JTextField txtCfname;
    private javax.swing.JTextField txtClname;
    private javax.swing.JTextField txtCpassword;
    private javax.swing.JTextField txtCphone;
    private javax.swing.JTextField txtCusername;
    private javax.swing.JTextField txtSemail;
    private javax.swing.JTextField txtSpassword;
    private javax.swing.JTextField txtSphone;
    private javax.swing.JTextField txtSusername;
    private javax.swing.JTextField txtcompanyname;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtproductprice;
    // End of variables declaration//GEN-END:variables

    // message methode
    public void setMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    // clearing the data
    
    public void clearFields1(){
        txtCusername.setText("");
        txtCfname.setText("");
        txtCemail.setText("");
        txtClname.setText("");
        txtCphone.setText("");
        txtCpassword.setText("");
    }
    
    public void clearFields2(){
        txtSusername.setText("");
        txtSemail.setText("");
        txtSphone.setText("");
        txtSpassword.setText("");
        txtcompanyname.setText("");
    }
    
    public void clearFields3(){
        txtpid.setText("");
        txtproductname.setText("");
        txtproductprice.setText("");
   }
}
