
package View;

import Controller.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Model.*;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.*;

/**
 *
 * @author rohan-manandhar
 */
public class AdminDashboard extends javax.swing.JFrame {
    DefaultTableModel dtm;
    AdminCdeleteModel model;
    AdminCreateCustomerModel Model ;
    AdminCreateSupModel initModel;
    AdminUpdateProductModel initModel1;
    private AdminCreateCustomerController Accc;
    private adminCdeleteController D1;
    private AdminCreateSupController initCont;
    private AdminUpdateProductController initCont1;
    private final AdminDeleteSupController initCont2;
    private final AdminDeleteProductController initCont3;
    
    private String username1;
    /**
     * Creates new form adminDashboard
     */
    public AdminDashboard() {
        initComponents();
        initCont2 = new AdminDeleteSupController(this);
        initCont3 = new AdminDeleteProductController(this);
    }
    public void setUsername(String username) {
        this.username1 = username;
    }   
    // sending data to model
    
    // cusDeleteID
    public AdminCdeleteModel getUser(){
        model = new AdminCdeleteModel(txtCdeleteid.getText());
        return model;
    }
    
    // cusModel
    public AdminCreateCustomerModel getCUser()
    {     
        String username = txtCusername.getText();
        String fname = txtCfname.getText();
        String lname = txtClname.getText();
        String email = txtCemail.getText();
        String phone = txtCphone.getText();
        String password = txtCpassword.getText();

        Model = new AdminCreateCustomerModel(username, fname, lname, email, phone, password);
        return Model;
    }
    
    // supModel
    public AdminCreateSupModel getSupUSer(){
        String username = txtSusername.getText();
        String companyname = txtcompanyname.getText();
        String email = txtSemail.getText();
        String phone = txtSphone.getText();
        String password = txtSpassword.getText();
        
        initModel = new AdminCreateSupModel(username, companyname, email, phone, password);
        return initModel;
    }
    
    // prodModel
    public AdminUpdateProductModel getProductdata(){
        int pid = Integer.parseInt(txtpid.getText());
        String productName = txtproductname.getText();
        double productPrice = Double.parseDouble(txtproductprice.getText());
        
        initModel1 = new AdminUpdateProductModel(pid, productName, productPrice);
        return initModel1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();
        txtCusername = new javax.swing.JTextField();
        txtCfname = new javax.swing.JTextField();
        txtCemail = new javax.swing.JTextField();
        txtCpassword = new javax.swing.JTextField();
        txtCphone = new javax.swing.JTextField();
        txtClname = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnCcreate = new javax.swing.JButton();
        btnCview = new javax.swing.JButton();
        txtCdeleteid = new javax.swing.JTextField();
        btnCdelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        suppliertable = new javax.swing.JTable();
        txtSusername = new javax.swing.JTextField();
        txtcompanyname = new javax.swing.JTextField();
        txtSemail = new javax.swing.JTextField();
        txtSpassword = new javax.swing.JTextField();
        txtSphone = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnScreate = new javax.swing.JButton();
        btnSview = new javax.swing.JButton();
        btnSdelete = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        txtpid = new javax.swing.JTextField();
        txtproductname = new javax.swing.JTextField();
        txtproductprice = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnPupdate = new javax.swing.JButton();
        btnPview = new javax.swing.JButton();
        btnPdelete = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("adminframe"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel2.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel2.setText("NexLogix");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to admin profile");

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel4.setText(": admin");

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel5.setText(": world");

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel6.setText("Admin username");

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel7.setText("Admin Password");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagePack/Adminimage.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Admin info", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        customertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        customertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Fname", "Lname", "Email", "Phone", "Password"
            }
        ));
        customertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(customertable);

        txtCusername.setBorder(null);
        txtCusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCusernameFocusLost(evt);
            }
        });

        txtCfname.setBorder(null);
        txtCfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCfnameFocusLost(evt);
            }
        });

        txtCemail.setBorder(null);
        txtCemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCemailFocusLost(evt);
            }
        });

        txtCpassword.setBorder(null);
        txtCpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpasswordFocusLost(evt);
            }
        });

        txtCphone.setBorder(null);
        txtCphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCphoneFocusLost(evt);
            }
        });

        txtClname.setBorder(null);
        txtClname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClnameFocusLost(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(221, 219, 219));

        btnCcreate.setBackground(new java.awt.Color(0, 153, 204));
        btnCcreate.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnCcreate.setText("Create user");
        btnCcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCcreateActionPerformed(evt);
            }
        });

        btnCview.setBackground(new java.awt.Color(0, 153, 204));
        btnCview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnCview.setText("View user");
        btnCview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCviewActionPerformed(evt);
            }
        });

        txtCdeleteid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCdeleteidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCdeleteidFocusLost(evt);
            }
        });

        btnCdelete.setBackground(new java.awt.Color(0, 153, 204));
        btnCdelete.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnCdelete.setText("Delete user");
        btnCdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCdeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCview, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCview, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(txtCdeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCemail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(txtCphone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCfname, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCusername, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtClname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator4))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCfname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtClname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCphone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Customer", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        suppliertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        suppliertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Company Name", "Email", "Phone", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        suppliertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(suppliertable);

        txtSusername.setBorder(null);
        txtSusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSusernameFocusLost(evt);
            }
        });

        txtcompanyname.setBorder(null);
        txtcompanyname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcompanynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcompanynameFocusLost(evt);
            }
        });

        txtSemail.setBorder(null);
        txtSemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSemailFocusLost(evt);
            }
        });

        txtSpassword.setBorder(null);
        txtSpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSpasswordFocusLost(evt);
            }
        });

        txtSphone.setBorder(null);
        txtSphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSphoneFocusLost(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(227, 223, 223));

        btnScreate.setBackground(new java.awt.Color(0, 153, 204));
        btnScreate.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnScreate.setText("Create user");
        btnScreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScreateActionPerformed(evt);
            }
        });

        btnSview.setBackground(new java.awt.Color(0, 153, 204));
        btnSview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnSview.setText("View user");
        btnSview.setBorder(null);
        btnSview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSviewActionPerformed(evt);
            }
        });

        btnSdelete.setBackground(new java.awt.Color(0, 153, 204));
        btnSdelete.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnSdelete.setText("Delete user");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnScreate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSview, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnScreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSview, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagePack/adminimage1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcompanyname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSusername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtSusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtSemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtSphone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        txtSusername.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Supplier", jPanel6);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        producttable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product name", "Product price", "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        producttable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(producttable);

        txtpid.setBorder(null);
        txtpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpidFocusLost(evt);
            }
        });

        txtproductname.setBorder(null);
        txtproductname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductnameFocusLost(evt);
            }
        });

        txtproductprice.setBorder(null);
        txtproductprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductpriceFocusLost(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(217, 215, 215));

        btnPupdate.setBackground(new java.awt.Color(0, 153, 204));
        btnPupdate.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnPupdate.setText("Update product");
        btnPupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPupdateActionPerformed(evt);
            }
        });

        btnPview.setBackground(new java.awt.Color(0, 153, 204));
        btnPview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnPview.setText("View products");
        btnPview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPviewActionPerformed(evt);
            }
        });

        btnPdelete.setBackground(new java.awt.Color(0, 153, 204));
        btnPdelete.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnPdelete.setText("Delete user");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPview, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPupdate))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnPupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnPview, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jSeparator12.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator13.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator14.setForeground(new java.awt.Color(102, 102, 102));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagePack/adminimage2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtproductname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtpid, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtproductprice, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator12)
                            .addComponent(jSeparator13)
                            .addComponent(jSeparator14))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtproductprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Product", jPanel8);

        btnLogout.setBackground(java.awt.SystemColor.controlDkShadow);
        btnLogout.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        btnLogout.setText("Boss Log out");
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(380, 380, 380))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Boss thanks for the Hardwork", "Admin logged out",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        Loginwin login = new Loginwin();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnCviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCviewActionPerformed
        AdminCdisplay Model = new AdminCdisplay();
        List<AdminCmodel> customerList = Model.getCustomerData();
        
        dtm = (DefaultTableModel)customertable.getModel();
        dtm.setRowCount(0);
        // Iterate over the customer list and access the data
        for (AdminCmodel customer : customerList) {
            
            // getting value from model
            String username = customer.getUsername();
            String fname = customer.getFname();
            String lname = customer.getLname();
            String email = customer.getEmail();
            String phone = customer.getPhone();
            String password = customer.getPassword();

            // creating a object with customer data
            Object[] rowData = {username, fname, lname, email, phone, password};

            // Add the row to the table model
            dtm.addRow((Object[]) rowData);
            System.out.println(username);
        }
            // checking this as alternative 
            //customertable.setModel(dtm);
    }//GEN-LAST:event_btnCviewActionPerformed

    private void btnCdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCdeleteActionPerformed
        if (D1 == null ){
            D1 = new adminCdeleteController(this);
        }
    }//GEN-LAST:event_btnCdeleteActionPerformed

    //setting some style with focusGained and FocusLost
    private void txtCdeleteidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCdeleteidFocusGained
    if (txtCdeleteid.getText().equals("Enter ID")){
            txtCdeleteid.setText("");
            txtCdeleteid.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCdeleteidFocusGained

    private void txtCdeleteidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCdeleteidFocusLost
        if (txtCdeleteid.getText().isEmpty()){
            txtCdeleteid.setText("Enter ID");
            txtCdeleteid.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtCdeleteidFocusLost

    private void txtCfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCfnameFocusGained
        if (txtCfname.getText().equals("First name: ")){
            txtCfname.setText("");
            txtCfname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCfnameFocusGained

    private void txtCfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCfnameFocusLost
        if (txtCfname.getText().equals("")){
            txtCfname.setText("First name: ");
            txtCfname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCfnameFocusLost

    private void txtClnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClnameFocusGained
        if (txtClname.getText().equals("Last Name: ")){
            txtClname.setText("");
            txtClname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtClnameFocusGained

    private void txtClnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClnameFocusLost
        if (txtClname.getText().equals("")){
            txtClname.setText("Last Name: ");
            txtClname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtClnameFocusLost

    private void txtCemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCemailFocusGained
        if (txtCemail.getText().equals("Email: ")){
            txtCemail.setText("");
            txtCemail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCemailFocusGained

    private void txtCemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCemailFocusLost
        if (txtCemail.getText().equals("")){
            txtCemail.setText("Email: ");
            txtCemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCemailFocusLost

    private void txtCphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCphoneFocusGained
        if (txtCphone.getText().equals("Phone number: ")){
            txtCphone.setText("");
            txtCphone.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCphoneFocusGained

    private void txtCphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCphoneFocusLost
    if (txtCphone.getText().equals("")){
            txtCphone.setText("Phone number: ");
            txtCphone.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCphoneFocusLost

    private void txtCpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpasswordFocusGained
    if (txtCpassword.getText().equals("Password: ")){
            txtCpassword.setText("");
            txtCpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCpasswordFocusGained

    private void txtCpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpasswordFocusLost
        if (txtCpassword.getText().equals("")){
                txtCpassword.setText("Password: ");
                txtCpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCpasswordFocusLost

    private void btnCcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCcreateActionPerformed
        if ( Accc == null){
            Accc = new AdminCreateCustomerController(this);
        }
    }//GEN-LAST:event_btnCcreateActionPerformed

    private void btnSviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSviewActionPerformed
        AdminGetSupDataModel model = new AdminGetSupDataModel();
        List<AdminSendSupDataModel> supplierList = model.getSupData();

        dtm = (DefaultTableModel) suppliertable.getModel();
        dtm.setRowCount(0);

        for (AdminSendSupDataModel supplier : supplierList) {
            String username = supplier.getUsername();
            String companyName = supplier.getCompanyname();
            String email = supplier.getEmail();
            String phone = supplier.getPhone();
            String password = supplier.getPassword();

            Object[] rowData = {username, companyName, email, phone, password};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_btnSviewActionPerformed

    private void btnPviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPviewActionPerformed
        AdminGetProdDataModel model = new AdminGetProdDataModel();
        List<AdminSendProdDataModel> productList = model.getProdData();

        dtm = (DefaultTableModel) producttable.getModel();
        dtm.setRowCount(0);

        for (AdminSendProdDataModel product : productList) {
            int pid = product.getPid();
            String productName = product.getProductname();
            double productPrice = product.getProductprice();
            String supplierName = product.getSuppliername();

            Object[] rowData = {pid, productName, productPrice, supplierName};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_btnPviewActionPerformed

    private void txtCusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCusernameFocusGained
        if (txtCusername.getText().equals("Username: ")){
            txtCusername.setText("");
            txtCusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCusernameFocusGained

    private void txtCusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCusernameFocusLost
        if (txtCusername.getText().equals("")){
            txtCusername.setText("Username: ");
            txtCusername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCusernameFocusLost

    private void txtSusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusGained
        if (txtSusername.getText().equals("Username: ")){
            txtSusername.setText("");
            txtSusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSusernameFocusGained

    private void txtSusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusLost
        if (txtSusername.getText().equals("")){
            txtSusername.setText("Username: ");
            txtSusername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSusernameFocusLost

    private void txtcompanynameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcompanynameFocusGained
        if (txtcompanyname.getText().equals("Company name: ")){
            txtcompanyname.setText("");
            txtcompanyname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcompanynameFocusGained

    private void txtcompanynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcompanynameFocusLost
        if (txtcompanyname.getText().equals("")){
            txtcompanyname.setText("Company name: ");
            txtcompanyname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcompanynameFocusLost

    private void txtSemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemailFocusGained
        if (txtSemail.getText().equals("Email: ")){
            txtSemail.setText("");
            txtSemail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSemailFocusGained

    private void txtSemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemailFocusLost
        if (txtSemail.getText().equals("")){
            txtSemail.setText("Email: ");
            txtSemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSemailFocusLost

    private void txtSphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSphoneFocusGained
        if (txtSphone.getText().equals("Phone Number: ")){
            txtSphone.setText("");
            txtSphone.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSphoneFocusGained

    private void txtSphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSphoneFocusLost
        if (txtSphone.getText().equals("")){
            txtSphone.setText("Phone Number: ");
            txtSphone.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSphoneFocusLost

    private void txtSpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSpasswordFocusGained
        if (txtSpassword.getText().equals("Password: ")){
            txtSpassword.setText("");
            txtSpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSpasswordFocusGained

    private void txtSpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSpasswordFocusLost
        if (txtSpassword.getText().equals("")){
            txtSpassword.setText("Password: ");
            txtSpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSpasswordFocusLost

    private void txtpidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusGained
        if (txtpid.getText().equals("Product ID: ")){
            txtpid.setText("");
            txtpid.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtpidFocusGained

    private void txtpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusLost
        if (txtpid.getText().equals("")){
            txtpid.setText("Product ID: ");
            txtpid.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpidFocusLost

    private void txtproductnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusGained
        if (txtproductname.getText().equals("Product name: ")){
            txtproductname.setText("");
            txtproductname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtproductnameFocusGained

    private void txtproductnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusLost
        if (txtproductname.getText().equals("")){
            txtproductname.setText("Product name: ");
            txtproductname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtproductnameFocusLost

    private void txtproductpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductpriceFocusGained
        if (txtproductprice.getText().equals("Product price: ")){
            txtproductprice.setText("");
            txtproductprice.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtproductpriceFocusGained

    private void txtproductpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductpriceFocusLost
        if (txtproductprice.getText().equals("")){
            txtproductprice.setText("Product price: ");
            txtproductprice.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtproductpriceFocusLost

    private void btnScreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScreateActionPerformed
        if( initCont == null ){
            initCont = new AdminCreateSupController(this);
        }
    }//GEN-LAST:event_btnScreateActionPerformed

    private void btnPupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPupdateActionPerformed
        if (initCont1 == null){
            initCont1 = new AdminUpdateProductController(this);
        }
    }//GEN-LAST:event_btnPupdateActionPerformed
    
    // adding Actionlistener for required 
    public void addLoginListner(ActionListener log){
        btnCdelete.addActionListener(log);
    } 
    
    public void addButtonListener(ActionListener log){
        btnCcreate.addActionListener(log); 
    }
    
    public void addCreateSupListener(ActionListener create){
        btnScreate.addActionListener(create);
    }
    
    public void addUpdateProdListerner( ActionListener update){
        btnPupdate.addActionListener(update);
    }
    
    public void addDeleteSupListener (ActionListener delete){
        btnSdelete.addActionListener(delete);
    }
    
    public void addDeleteProdListener (ActionListener delete){
        btnPdelete.addActionListener(delete);
    }
    
    // sending the value 
    
    public JButton getBtnDeleteSup (){
        return btnSdelete;
    }
    
    public JButton getBtnDeleteProd(){
        return btnPdelete;
    }
    
    public JTable getSupTable(){
        return suppliertable;
    }
    
    public JTable getProductTable(){
        return producttable;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCcreate;
    private javax.swing.JButton btnCdelete;
    private javax.swing.JButton btnCview;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPdelete;
    private javax.swing.JButton btnPupdate;
    private javax.swing.JButton btnPview;
    private javax.swing.JButton btnScreate;
    private javax.swing.JButton btnSdelete;
    private javax.swing.JButton btnSview;
    private javax.swing.JTable customertable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable producttable;
    private javax.swing.JTable suppliertable;
    private javax.swing.JTextField txtCdeleteid;
    private javax.swing.JTextField txtCemail;
    private javax.swing.JTextField txtCfname;
    private javax.swing.JTextField txtClname;
    private javax.swing.JTextField txtCpassword;
    private javax.swing.JTextField txtCphone;
    private javax.swing.JTextField txtCusername;
    private javax.swing.JTextField txtSemail;
    private javax.swing.JTextField txtSpassword;
    private javax.swing.JTextField txtSphone;
    private javax.swing.JTextField txtSusername;
    private javax.swing.JTextField txtcompanyname;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtproductprice;
    // End of variables declaration//GEN-END:variables

    // message methode
    public void setMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    // clearing the data
    
    public void clearFields1(){
        txtCusername.setText("");
        txtCfname.setText("");
        txtCemail.setText("");
        txtClname.setText("");
        txtCphone.setText("");
        txtCpassword.setText("");
    }
    
    public void clearFields2(){
        txtSusername.setText("");
        txtSemail.setText("");
        txtSphone.setText("");
        txtSpassword.setText("");
        txtcompanyname.setText("");
    }
    
    public void clearFields3(){
        txtpid.setText("");
        txtproductname.setText("");
        txtproductprice.setText("");
   }
}
