
package View;

import Model.*;
import Controller.*;
import Database.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class customerDashboard extends javax.swing.JFrame {
    DefaultTableModel dtm;
    CupdateFrame frame;
    private CustomerOrderController controller;
    private CustomerOrderModel model;
    private CusUpdateSelfModel model1;
    private final CustomerDeleteOrderController controller1;
    CusUpdateSelfController controller2;
    private final CusDeleteSelfController controller3;
    
    private String username1; // for passing the name;
    /**
     * Creates new form customerDashboard
     */
    public customerDashboard() {
        initComponents();
        controller1 = new CustomerDeleteOrderController(this);
        controller3 = new CusDeleteSelfController(this);
    }
    public void setUsername(String username) {
        this.username1 = username;
    }
    // Sending data
    public CustomerOrderModel getOrder(){
        String cusername = txtcusername.getText();
        int pid = Integer.parseInt(txtpid.getText());
        String susername = txtSusername.getText();
        
        model = new CustomerOrderModel(cusername, pid, susername);
        return model;
    }
    
    // show message
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cusTable = new javax.swing.JTable();
        txtUusername = new javax.swing.JTextField();
        txtUfname = new javax.swing.JTextField();
        txtUlname = new javax.swing.JTextField();
        txtUpassword = new javax.swing.JTextField();
        txtUemail = new javax.swing.JTextField();
        txtUphone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnFetch = new javax.swing.JButton();
        txtdeleteid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeleteId = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        itemPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cproducttable = new javax.swing.JTable();
        txtcusername = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        txtSusername = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAddOrder = new javax.swing.JButton();
        btnproductview = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ordertable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnDeleteOrder = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnvieworder = new javax.swing.JButton();
        txtousername = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Dashboard");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));

        cusTable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        cusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "F_name", "L_name", "Email", "Phone", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(cusTable);

        txtUusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUusername.setBorder(null);
        txtUusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUusernameFocusLost(evt);
            }
        });

        txtUfname.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUfname.setBorder(null);
        txtUfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUfnameFocusLost(evt);
            }
        });

        txtUlname.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUlname.setBorder(null);
        txtUlname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUlnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUlnameFocusLost(evt);
            }
        });

        txtUpassword.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUpassword.setBorder(null);
        txtUpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUpasswordFocusLost(evt);
            }
        });

        txtUemail.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUemail.setBorder(null);
        txtUemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUemailFocusLost(evt);
            }
        });

        txtUphone.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUphone.setBorder(null);
        txtUphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUphoneFocusLost(evt);
            }
        });

        btnFetch.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnFetch.setText("Fetch data");
        btnFetch.setBorder(null);
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });

        txtdeleteid.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtdeleteid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdeleteidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdeleteidFocusLost(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jButton3.setText("Update username");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnUpdate.setText("Update ID");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDeleteId.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnDeleteId.setText("Delete ID");
        btnDeleteId.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFetch, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(txtdeleteid, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtdeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagePack/customerprofile.png"))); // NOI18N

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(txtUusername, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtUemail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtUphone, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtUpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtUfname)
                            .addComponent(txtUlname)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addComponent(txtUusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(txtUfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtUlname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtUphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("My profile", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        itemPanel.setBackground(new java.awt.Color(255, 255, 255));

        cproducttable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        cproducttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PID", "Product Name", "Product Price", "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(cproducttable);

        txtcusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtcusername.setBorder(null);
        txtcusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcusernameFocusLost(evt);
            }
        });

        txtpid.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtpid.setBorder(null);
        txtpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpidFocusLost(evt);
            }
        });

        txtSusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtSusername.setBorder(null);
        txtSusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSusernameFocusLost(evt);
            }
        });

        btnAddOrder.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnAddOrder.setText("Add Order");
        btnAddOrder.setBorder(null);
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        btnproductview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnproductview.setText("View Product");
        btnproductview.setBorder(null);
        btnproductview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnproductview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnproductview, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jLabel3.setText("Username :");

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jLabel4.setText("Product Name :");

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jLabel5.setText("Supplier Name :");

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpid, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator8)
                            .addComponent(txtSusername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtcusername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator9)
                            .addComponent(jSeparator10)))
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPanelLayout.createSequentialGroup()
                        .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemPanelLayout.createSequentialGroup()
                                .addComponent(txtSusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)))
                        .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Item", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        detailPanel.setBackground(new java.awt.Color(255, 255, 255));

        Ordertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        Ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Customer Name", "Product ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Ordertable);

        btnDeleteOrder.setBackground(new java.awt.Color(153, 153, 255));
        btnDeleteOrder.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnDeleteOrder.setText("Delete order");
        btnDeleteOrder.setBorder(null);

        btnPrint.setBackground(new java.awt.Color(153, 153, 255));
        btnPrint.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnvieworder.setBackground(new java.awt.Color(153, 153, 255));
        btnvieworder.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnvieworder.setText("View order");
        btnvieworder.setBorder(null);
        btnvieworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvieworderActionPerformed(evt);
            }
        });

        txtousername.setBackground(new java.awt.Color(242, 242, 242));
        txtousername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtousername.setBorder(null);
        txtousername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtousernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtousernameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(btnvieworder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtousername, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(txtousername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnvieworder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Oder detail", jPanel5);

        jLabel1.setFont(new java.awt.Font("Noto Serif CJK KR", 1, 36)); // NOI18N
        jLabel1.setText("NexLogix");

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("NTR", 1, 20)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnproductviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductviewActionPerformed
        
        CuspDisplayModel Model = new CuspDisplayModel();
        // Getting the value
        List <CusProductViewModel> productList = Model.getProductData();
        
        dtm = (DefaultTableModel) cproducttable.getModel();
        
        // Clear existing rows in the table
        dtm.setRowCount(0);

        // Iterate over the product list and access the data
        for (CusProductViewModel product : productList) {
            int pid = product.getPid();
            String productName = product.getProductname();
            double productPrice = product.getProductprice();
            String supplierUsername = product.getSuppplierusername();

            // Create an object with product data
            Object[] rowData = {pid, productName, productPrice, supplierUsername};

            // Add the row to the table model
            dtm.addRow((Object[]) rowData);
        }
    }//GEN-LAST:event_btnproductviewActionPerformed

    private void txtcusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcusernameFocusGained
        if (txtcusername.getText().equals("Enter your username: "))
        {
            txtcusername.setText("");
            txtcusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtcusernameFocusGained

    private void txtcusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcusernameFocusLost
        if (txtcusername.getText().equals(""))
        {
            txtcusername.setText("Enter your username: ");
            txtcusername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtcusernameFocusLost

    private void txtpidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusGained
        if (txtpid.getText().equals("Enter Product ID:"))
        {
            txtpid.setText("");
            txtpid.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtpidFocusGained

    private void txtpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusLost
        if (txtpid.getText().equals(""))
        {
            txtpid.setText("Enter Product ID:");
            txtpid.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtpidFocusLost

    private void txtSusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusGained
        if (txtSusername.getText().equals("Enter supplier name: "))
        {
            txtSusername.setText("");
            txtSusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSusernameFocusGained

    private void txtSusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusLost
        if (txtSusername.getText().equals(""))
        {
            txtSusername.setText("Enter supplier name: ");
            txtSusername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSusernameFocusLost

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        if (controller == null){
            controller = new CustomerOrderController(this);
        }
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void txtousernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtousernameFocusGained
        if (txtousername.getText().equals("Username:")){
            txtousername.setText("");
            txtousername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtousernameFocusGained

    private void txtousernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtousernameFocusLost
        if (txtousername.getText().equals("")){
            txtousername.setText("Username:");
            txtousername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtousernameFocusLost

    private void btnvieworderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvieworderActionPerformed
        String username = txtousername.getText(); // Get the username from the text field
        if (username.isEmpty()) {
        // Displaying an error message if the username is empty
        JOptionPane.showMessageDialog(null, "Please enter a valid customer name.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        CustomerOrderViewModel Model = new CustomerOrderViewModel();
        List <CustomerOrderDataModel> orderList = Model.getOrderData(username); // Getting the value
        
        if (orderList.isEmpty()) {
        // Displaying a message if no order data found for the customer
        JOptionPane.showMessageDialog(null, "No order data found for the specified customer.", "No Data", JOptionPane.INFORMATION_MESSAGE);
        return;
        }

        dtm = (DefaultTableModel)Ordertable.getModel();
        dtm.setRowCount(0);
        
        for (CustomerOrderDataModel order : orderList) {
            int orderid = order.getOrderid();
            String customername = order.getCustomername();
            int productid = order.getProductid();
            
            Object[] rowData = {orderid, customername, productid};
            dtm.addRow((Object[]) rowData);
        }
    }//GEN-LAST:event_btnvieworderActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (controller2 == null){
            controller2 = new CusUpdateSelfController(this);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
        String id = txtdeleteid.getText();
        
        if (id.isEmpty()) {
            // Displaying an error message if the username is empty
            JOptionPane.showMessageDialog(null, "Please enter a valid customer name.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CusGetOwnInfoDatabase database = new CusGetOwnInfoDatabase();
        List<CusOwnDataModel> customerList = database.getCustomerData(id);

        if (!customerList.isEmpty()) {
            // Display customer data in the cusTable
            dtm = (DefaultTableModel) cusTable.getModel();
            dtm.setRowCount(0);

            for (CusOwnDataModel customer : customerList) {
                String username = customer.getUsername();
                String fname = customer.getFname();
                String lname = customer.getLname();
                String email = customer.getEmail();
                String phone = customer.getPhone();
                String password = customer.getPassword();

                Object[] rowData = {username, fname, lname, email, phone, password};
                dtm.addRow(rowData);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No customer data found for the given ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFetchActionPerformed

    private void txtUusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUusernameFocusGained
        if (txtUusername.getText().equals("Registered Username:")){
            txtUusername.setText("");
            txtUusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUusernameFocusGained

    private void txtUusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUusernameFocusLost
        if (txtUusername.getText().equals("")){
            txtUusername.setText("Registered Username:");
            txtUusername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUusernameFocusLost

    private void txtUfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUfnameFocusGained
        if (txtUfname.getText().equals("New First name:")){
            txtUfname.setText("");
            txtUfname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUfnameFocusGained

    private void txtUfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUfnameFocusLost
        if (txtUfname.getText().equals("")){
            txtUfname.setText("New First name:");
            txtUfname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUfnameFocusLost

    private void txtUemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUemailFocusGained
        if (txtUemail.getText().equals("New Email:")){
            txtUemail.setText("");
            txtUemail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUemailFocusGained

    private void txtUemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUemailFocusLost
        if (txtUemail.getText().equals("")){
            txtUemail.setText("New Email:");
            txtUemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUemailFocusLost

    private void txtUlnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUlnameFocusGained
        if (txtUlname.getText().equals("New Last name:")){
            txtUlname.setText("");
            txtUlname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUlnameFocusGained

    private void txtUlnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUlnameFocusLost
        if (txtUlname.getText().equals("")){
            txtUlname.setText("New Last name:");
            txtUlname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUlnameFocusLost

    private void txtUphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUphoneFocusGained
        if (txtUphone.getText().equals("New Phone Number:")){
            txtUphone.setText("");
            txtUphone.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUphoneFocusGained

    private void txtUphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUphoneFocusLost
        if (txtUphone.getText().equals("")){
            txtUphone.setText("New Phone Number:");
            txtUphone.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUphoneFocusLost

    private void txtUpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpasswordFocusGained
        if (txtUpassword.getText().equals("New password:")){
            txtUpassword.setText("");
            txtUpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUpasswordFocusGained

    private void txtUpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpasswordFocusLost
        if (txtUpassword.getText().equals("")){
            txtUpassword.setText("New password:");
            txtUpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUpasswordFocusLost

    private void txtdeleteidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdeleteidFocusGained
        if (txtdeleteid.getText().equals("Username: ")){
            txtdeleteid.setText("");
            txtdeleteid.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtdeleteidFocusGained

    private void txtdeleteidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdeleteidFocusLost
        if (txtdeleteid.getText().equals("")){
            txtdeleteid.setText("Username: ");
            txtdeleteid.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtdeleteidFocusLost

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Timer timer = new Timer(3000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            openUpdateFrame();
            }
        });

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
            // TODO add your handling code here:
        MessageFormat header = new MessageFormat(":::  Customers Order Data :::");
        MessageFormat footer = new MessageFormat("Nexlogix, A powerful Supply Chain M<anagement System");
        try{
            Ordertable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        }
        catch (PrinterException e){
            JOptionPane.showMessageDialog(null,"Error! Cannot Print"+e.getMessage());
            
        }
    }//GEN-LAST:event_btnPrintActionPerformed
    
    // cus-Update Model
    public CusUpdateSelfModel getCdata(){
        String txtusername = txtUusername.getText();
        String txtfname = txtUfname.getText();
        String txtlname = txtUlname.getText();
        String txtemail = txtUemail.getText();
        String txtphone = txtUphone.getText();
        String txtpassword = txtUpassword.getText();
        
        model1 = new CusUpdateSelfModel(txtusername, txtfname, txtlname, txtemail, txtphone, txtpassword);
        return model1;
    }
    
        // actionListener
    public void addOrderButtonListener(ActionListener listener) {
        btnAddOrder.addActionListener(listener);
    }
    
    public void AddDeleteButtonLIstener(ActionListener listener){
        btnDeleteOrder.addActionListener(listener);
    }
    
    public void AddSelfDeleteListener(ActionListener delete){
        btnDeleteId.addActionListener(delete);
    }
    
    // buttons action
    public JButton getBtnAddOrder(){
        return btnAddOrder;
    }
    
    public JButton getBtnDeleteOrder(){
        return btnDeleteOrder;
    }
    
    public JButton getDeleteButton(){
        return btnDeleteId;
    }
    
    // Sending Tabledata
    public JTable getOrderTable (){
        return Ordertable;
    }
    
    public JTable getCusTable(){
        return cusTable;
    }
    
    // clear fields
    public void orderclearFields(){
        txtcusername.setText("");
        txtSusername.setText("");
        txtpid.setText("");
    }
    
    public void ClearMeData(){
        txtUusername.setText("");
        txtUfname.setText("");
        txtUlname.setText("");
        txtUemail.setText("");
        txtUphone.setText("");
        txtUpassword.setText("");
    }
    // Messages
    public void displayErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void displaySuccessMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new customerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordertable;
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDeleteId;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnFetch;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnproductview;
    private javax.swing.JButton btnvieworder;
    private javax.swing.JTable cproducttable;
    private javax.swing.JTable cusTable;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JTextField txtSusername;
    private javax.swing.JTextField txtUemail;
    private javax.swing.JTextField txtUfname;
    private javax.swing.JTextField txtUlname;
    private javax.swing.JTextField txtUpassword;
    private javax.swing.JTextField txtUphone;
    private javax.swing.JTextField txtUusername;
    private javax.swing.JTextField txtcusername;
    private javax.swing.JTextField txtdeleteid;
    private javax.swing.JTextField txtousername;
    private javax.swing.JTextField txtpid;
    // End of variables declaration//GEN-END:variables

    // actionListener
    public void AddUpdateButtonListener(ActionListener listener) {
        btnUpdate.addActionListener(listener);
    }
    
    private void openUpdateFrame() {
        frame = new CupdateFrame();
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                frame.dispose(); // Only close the update frame
            }
        });
        frame.setVisible(true);
    }
}
