
package View;

import Model.*;
import Controller.*;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class customerDashboard extends javax.swing.JFrame {
    DefaultTableModel dtm;
    CustomerOrderController controller;
    CustomerOrderModel model;
    private CustomerDeleteOrderController controller1;
    /**
     * Creates new form customerDashboard
     */
    public customerDashboard() {
        initComponents();
        controller1 = new CustomerDeleteOrderController(this);
    }
    
    // Sending data
    public CustomerOrderModel getOrder(){
        String cusername = txtcusername.getText();
        int pid = Integer.parseInt(txtpid.getText());
        String susername = txtSusername.getText();
        
        model = new CustomerOrderModel(cusername, pid, susername);
        return model;
    }
    
    // show message
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        producttable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtUusername = new javax.swing.JTextField();
        txtdeleteid = new javax.swing.JTextField();
        txtUfname = new javax.swing.JTextField();
        txtUlname = new javax.swing.JTextField();
        txtUpassword = new javax.swing.JTextField();
        txtUemail = new javax.swing.JTextField();
        txtUphone = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        itemPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cproducttable = new javax.swing.JTable();
        btnproductview = new javax.swing.JButton();
        btnAddOrder = new javax.swing.JButton();
        txtcusername = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        txtSusername = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ordertable = new javax.swing.JTable();
        btnvieworder = new javax.swing.JButton();
        txtousername = new javax.swing.JTextField();
        btnDeleteOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Dashboard");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 23, 139));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        producttable1.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        producttable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "F_name", "L_name", "Email", "Phone", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(producttable1);

        jButton1.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jButton1.setText("Fetch data");
        jButton1.setBorder(null);

        jButton2.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jButton2.setText("Update ID");
        jButton2.setBorder(null);

        jButton3.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jButton3.setText("Delete ID");
        jButton3.setBorder(null);

        txtUusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUusername.setText("Username");

        txtdeleteid.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtdeleteid.setText("Delete ID");

        txtUfname.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUfname.setText("First name");

        txtUlname.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUlname.setText("Last name");

        txtUpassword.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUpassword.setText("Password");

        txtUemail.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUemail.setText("Email");

        txtUphone.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUphone.setText("Phone number");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(494, 494, 494))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118)
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUusername, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUphone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUemail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(txtUfname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtUlname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtUlname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(txtUphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtdeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My profile", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        cproducttable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        cproducttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PID", "Product Name", "Product Price", "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(cproducttable);

        btnproductview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnproductview.setText("View Product");
        btnproductview.setBorder(null);
        btnproductview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductviewActionPerformed(evt);
            }
        });

        btnAddOrder.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnAddOrder.setText("Add Order");
        btnAddOrder.setBorder(null);
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        txtcusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtcusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcusernameFocusLost(evt);
            }
        });

        txtpid.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpidFocusLost(evt);
            }
        });

        txtSusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtSusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSusernameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(itemPanelLayout.createSequentialGroup()
                            .addComponent(btnproductview, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(84, 84, 84)
                            .addComponent(txtcusername, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                        .addGroup(itemPanelLayout.createSequentialGroup()
                            .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(84, 84, 84)
                            .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtpid, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(txtSusername)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproductview, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Item", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        Ordertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        Ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order Id", "Customer name", "Product Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Ordertable);

        btnvieworder.setBackground(new java.awt.Color(153, 153, 255));
        btnvieworder.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnvieworder.setText("View order");
        btnvieworder.setBorder(null);
        btnvieworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvieworderActionPerformed(evt);
            }
        });

        txtousername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtousername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtousernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtousernameFocusLost(evt);
            }
        });

        btnDeleteOrder.setBackground(new java.awt.Color(153, 153, 255));
        btnDeleteOrder.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnDeleteOrder.setText("Delete order");
        btnDeleteOrder.setBorder(null);

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtousername, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnvieworder, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvieworder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtousername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Oder detail", jPanel5);

        jLabel1.setFont(new java.awt.Font("Noto Serif CJK KR", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to Customer Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnproductviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductviewActionPerformed
        
        CuspDisplayModel Model = new CuspDisplayModel();
        // Getting the value
        List <CusProductViewModel> productList = Model.getProductData();
        
        dtm = (DefaultTableModel) cproducttable.getModel();
        
        // Clear existing rows in the table
        dtm.setRowCount(0);

        // Iterate over the product list and access the data
        for (CusProductViewModel product : productList) {
            int pid = product.getPid();
            String productName = product.getProductname();
            double productPrice = product.getProductprice();
            String supplierUsername = product.getSuppplierusername();

            // Create an object with product data
            Object[] rowData = {pid, productName, productPrice, supplierUsername};

            // Add the row to the table model
            dtm.addRow((Object[]) rowData);
        }
    }//GEN-LAST:event_btnproductviewActionPerformed

    private void txtcusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcusernameFocusGained
        if (txtcusername.getText().equals("Enter your username: "))
        {
            txtcusername.setText("");
            txtcusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtcusernameFocusGained

    private void txtcusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcusernameFocusLost
        if (txtcusername.getText().equals(""))
        {
            txtcusername.setText("Enter your username: ");
            txtcusername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtcusernameFocusLost

    private void txtpidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusGained
        if (txtpid.getText().equals("Enter Product ID:"))
        {
            txtpid.setText("");
            txtpid.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtpidFocusGained

    private void txtpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusLost
        if (txtpid.getText().equals(""))
        {
            txtpid.setText("Enter Product ID:");
            txtpid.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtpidFocusLost

    private void txtSusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusGained
        if (txtSusername.getText().equals("Enter supplier name: "))
        {
            txtSusername.setText("");
            txtSusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSusernameFocusGained

    private void txtSusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusernameFocusLost
        if (txtSusername.getText().equals(""))
        {
            txtSusername.setText("Enter supplier name: ");
            txtSusername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSusernameFocusLost

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        if (controller == null){
            controller = new CustomerOrderController(this);
        }
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void txtousernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtousernameFocusGained
        if (txtousername.getText().equals("Username:")){
            txtousername.setText("");
            txtousername.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtousernameFocusGained

    private void txtousernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtousernameFocusLost
        if (txtousername.getText().equals("")){
            txtousername.setText("Username:");
            txtousername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtousernameFocusLost

    private void btnvieworderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvieworderActionPerformed
        String username = txtousername.getText(); // Get the username from the text field
        if (username.isEmpty()) {
        // Displaying an error message if the username is empty
        JOptionPane.showMessageDialog(null, "Please enter a valid customer name.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        CustomerOrderViewModel Model = new CustomerOrderViewModel();
        List <CustomerOrderDataModel> orderList = Model.getOrderData(username); // Getting the value
        
        if (orderList.isEmpty()) {
        // Displaying a message if no order data found for the customer
        JOptionPane.showMessageDialog(null, "No order data found for the specified customer.", "No Data", JOptionPane.INFORMATION_MESSAGE);
        return;
        }

        dtm = (DefaultTableModel)Ordertable.getModel();
        dtm.setRowCount(0);
        
        for (CustomerOrderDataModel order : orderList) {
            int orderid = order.getOrderid();
            String customername = order.getCustomername();
            int productid = order.getProductid();
            
            Object[] rowData = {orderid, customername, productid};
            dtm.addRow((Object[]) rowData);
        }
    }//GEN-LAST:event_btnvieworderActionPerformed
    
    // actionListener
    public void addOrderButtonListener(ActionListener listener) {
        btnAddOrder.addActionListener(listener);
    }
    
    public void AddDeleteButtonLIstener(ActionListener listener){
        btnDeleteOrder.addActionListener(listener);
    }
    
    // buttons action
    public JButton getBtnAddOrder(){
        return btnAddOrder;
    }
    
    public JButton getBtnDeleteOrder(){
        return btnDeleteOrder;
    }
    
    // Sending Tabledata
    public JTable getOrderTable (){
        return Ordertable;
    }
    
    // clear fields
    public void orderclearFields(){
        txtcusername.setText("");
        txtSusername.setText("");
        txtpid.setText("");
    }
    // Messages
    public void displayErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void displaySuccessMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new customerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordertable;
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnproductview;
    private javax.swing.JButton btnvieworder;
    private javax.swing.JTable cproducttable;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable producttable1;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JTextField txtSusername;
    private javax.swing.JTextField txtUemail;
    private javax.swing.JTextField txtUfname;
    private javax.swing.JTextField txtUlname;
    private javax.swing.JTextField txtUpassword;
    private javax.swing.JTextField txtUphone;
    private javax.swing.JTextField txtUusername;
    private javax.swing.JTextField txtcusername;
    private javax.swing.JTextField txtdeleteid;
    private javax.swing.JTextField txtousername;
    private javax.swing.JTextField txtpid;
    // End of variables declaration//GEN-END:variables

}
