
package View;

import javax.swing.*;
import Model.*;
import Controller.*;
import Database.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.*;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class supplierDashboard extends javax.swing.JFrame {
    SupdateFrame frame;
    DefaultTableModel dtm;
    SupplierAddProductModel Model;
    SupUpdateSelfModel callModel;
    SupUpdateProductModel callModel1;
    private SupplierAddProductController S1;
    private final SupDeleteProductController controller;
    private SupUpdateSelfController concall;
    private SupUpdateProductController initCont;
    private final SupDeleteSelfController initCont1;
    
    private String username1; // for passing the name
    /**
     * Creates new form supplierDashboard
     */
    public supplierDashboard() {
        initComponents();
        controller = new SupDeleteProductController(this);
        initCont1 = new SupDeleteSelfController(this);
    }
    public void setUsername(String username) {
        this.username1 = username;
    }
    
    // sending data to model 
    public SupplierAddProductModel getProduct()
    {
        String productName = txtproductname.getText();
        double productPrice = Double.parseDouble(txtproductprice.getText());
        String supplierName = txtsuppliername.getText();

        Model = new SupplierAddProductModel(productName, productPrice, supplierName);
        return Model;
    }
    
    public SupUpdateSelfModel getSdata(){
        String username = txtUusername.getText();
        String companyname = txtUcompanyname.getText();
        String email = txtUemail.getText();
        String phone = txtUphone.getText();
        String password = txtUpassword.getText();
        
        callModel = new SupUpdateSelfModel(username, companyname, email, phone, password);
        return callModel;
    }
    
    public SupUpdateProductModel getProductData(){
        int pid = Integer.parseInt(txtPid.getText());
        String productname = txtproductname.getText();
        double productPrice = Double.parseDouble(txtproductprice.getText());
        
        callModel1 = new SupUpdateProductModel(pid, productname, productPrice);
        return callModel1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        btnaddProduct = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        btnProductView = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        txtproductname = new javax.swing.JTextField();
        txtproductprice = new javax.swing.JTextField();
        txtsuppliername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtPid = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sOrdertable = new javax.swing.JTable();
        btnorderview = new javax.swing.JButton();
        txtCheck = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSelfUpdate = new javax.swing.JButton();
        btnDeleteProfile = new javax.swing.JButton();
        btnSview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        profiletable = new javax.swing.JTable();
        txtSupid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUusername = new javax.swing.JTextField();
        txtUcompanyname = new javax.swing.JTextField();
        txtUemail = new javax.swing.JTextField();
        txtUphone = new javax.swing.JTextField();
        txtUpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supplier Dashboard");

        mainPanel.setBackground(new java.awt.Color(149, 173, 217));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        producttable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Product name", "Product price", "Supplier name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        producttable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(producttable);

        btnaddProduct.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnaddProduct.setText("Add product");
        btnaddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddProductActionPerformed(evt);
            }
        });

        btnUpdateProduct.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });

        btnProductView.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnProductView.setText("View Product");
        btnProductView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductViewActionPerformed(evt);
            }
        });

        btnDeleteProduct.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnDeleteProduct.setText("Delete Product");

        txtproductname.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtproductname.setBorder(null);
        txtproductname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductnameFocusLost(evt);
            }
        });

        txtproductprice.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtproductprice.setBorder(null);
        txtproductprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductpriceFocusLost(evt);
            }
        });

        txtsuppliername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtsuppliername.setBorder(null);
        txtsuppliername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsuppliernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsuppliernameFocusLost(evt);
            }
        });

        txtPid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPidFocusLost(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProductView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnaddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPid)
                            .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtproductprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txtsuppliername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3)))
                        .addGap(86, 86, 86))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnaddProduct)
                        .addGap(7, 7, 7)
                        .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateProduct)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtproductprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProductView))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsuppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnDeleteProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Products", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        sOrdertable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        sOrdertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order Id", "Customer name", "Product Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(sOrdertable);

        btnorderview.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnorderview.setText("View order");
        btnorderview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderviewActionPerformed(evt);
            }
        });

        txtCheck.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtCheck.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCheckFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCheckFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnorderview, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnorderview, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Orders", jPanel5);

        jPanel3.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));

        btnSelfUpdate.setBackground(new java.awt.Color(153, 153, 153));
        btnSelfUpdate.setFont(new java.awt.Font("Rasa", 0, 18)); // NOI18N
        btnSelfUpdate.setText("Update");
        btnSelfUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelfUpdateActionPerformed(evt);
            }
        });

        btnDeleteProfile.setBackground(new java.awt.Color(153, 153, 153));
        btnDeleteProfile.setFont(new java.awt.Font("Rasa", 0, 18)); // NOI18N
        btnDeleteProfile.setText("Delete Account");

        btnSview.setBackground(new java.awt.Color(153, 153, 153));
        btnSview.setFont(new java.awt.Font("Rasa", 0, 18)); // NOI18N
        btnSview.setText("View My Data");
        btnSview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSviewActionPerformed(evt);
            }
        });

        profiletable.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        profiletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "Company Name", "Email", "Phone", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(profiletable);

        txtSupid.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtSupid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSupidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupidFocusLost(evt);
            }
        });

        jLabel2.setText("Image");

        txtUusername.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUusernameFocusLost(evt);
            }
        });

        txtUcompanyname.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUcompanyname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUcompanynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUcompanynameFocusLost(evt);
            }
        });

        txtUemail.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUemailFocusLost(evt);
            }
        });

        txtUphone.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUphoneFocusLost(evt);
            }
        });

        txtUpassword.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        txtUpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUpasswordFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jButton1.setText("Update Username");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnSelfUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSupid))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUusername, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUemail, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtUphone))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnSview, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtSupid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelfUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Profile", jPanel3);

        jLabel1.setFont(new java.awt.Font("Liberation Mono", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Supplier");

        btnlogout.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        btnlogout.setText("Logout here...");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        JOptionPane.showMessageDialog(this, "Thanks for the hardwork", "supplier", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnaddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddProductActionPerformed
        if (S1 == null) {
        S1 = new SupplierAddProductController(this);
        }
    }//GEN-LAST:event_btnaddProductActionPerformed

    private void txtproductpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductpriceFocusGained
        if (txtproductprice.getText().equals("Enter Product Price"))
        {
            txtproductprice.setText("");
            txtproductprice.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtproductpriceFocusGained

    private void txtproductpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductpriceFocusLost
        if (txtproductprice.getText().equals(""))
        {
            txtproductprice.setText("Enter Product Price");
            txtproductprice.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtproductpriceFocusLost

    private void txtsuppliernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsuppliernameFocusGained
        if (txtsuppliername.getText().equals("Enter Supplier Name"))
        {
            txtsuppliername.setText("");
            txtsuppliername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtsuppliernameFocusGained

    private void txtsuppliernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsuppliernameFocusLost
        if (txtsuppliername.getText().equals(""))
        {
            txtsuppliername.setText("Enter Supplier Name");
            txtsuppliername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtsuppliernameFocusLost

    private void txtproductnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusGained
        if (txtproductname.getText().equals("Enter Product Name "))
        {
            txtproductname.setText("");
            txtproductname.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtproductnameFocusGained

    private void txtproductnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusLost
        if (txtproductname.getText().equals(""))
        {
            txtproductname.setText("Enter Product Name ");
            txtproductname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtproductnameFocusLost

    private void btnProductViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductViewActionPerformed
        pViewModel Model = new pViewModel();
        // Getting the value
        List <SupplierViewProductModel> productList = Model.getProductData();
        
        dtm = (DefaultTableModel) producttable.getModel();
        
        // Clear existing rows in the table
        dtm.setRowCount(0);

        // Iterate over the product list and access the data
        for (SupplierViewProductModel product : productList) {
            int pid = product.getPid();
            String productName = product.getProductname();
            double productPrice = product.getProductprice();
            String supplierUsername = product.getSuppplierusername();

            // Create an object with product data
            Object[] rowData = {pid, productName, productPrice, supplierUsername};

            // Add the row to the table model
            dtm.addRow((Object[]) rowData);
        }
    }//GEN-LAST:event_btnProductViewActionPerformed

    private void btnorderviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderviewActionPerformed
        String checkId = txtCheck.getText();
        
        if (checkId.isEmpty()) {
            // Displaying an error message if the check ID is empty
            JOptionPane.showMessageDialog(null, "Please enter a valid check ID.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SupOrderViewModel model = new SupOrderViewModel();
        List<SupOrderDataModel> orderList = model.getOrderData(checkId); // Getting the order data

        if (orderList.isEmpty()) {
            // Displaying a message if no order data found for the check ID
            JOptionPane.showMessageDialog(null, "No order data found for the specified check ID.", "No Data", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        dtm = (DefaultTableModel) sOrdertable.getModel();
        dtm.setRowCount(0);

        for (SupOrderDataModel order : orderList) {
            int orderId = order.getOrderid();
            String customerName = order.getCustomername();
            int productId = order.getProductid();

            Object[] rowData = {orderId, customerName, productId};
            dtm.addRow(rowData);
            }  
    }//GEN-LAST:event_btnorderviewActionPerformed

    private void txtCheckFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckFocusGained
        if (txtCheck.getText().equals("Enter your ID: "))
        {
            txtCheck.setText("");
            txtCheck.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCheckFocusGained

    private void txtCheckFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckFocusLost
        if (txtCheck.getText().equals(""))
        {
            txtCheck.setText("Enter your ID: ");
            txtCheck.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCheckFocusLost

    private void txtUusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUusernameFocusGained
        if (txtUusername.getText().equals("Your Username:"))
        {
            txtUusername.setText("");
            txtUusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUusernameFocusGained

    private void txtUusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUusernameFocusLost
        if (txtUusername.getText().equals(""))
        {
            txtUusername.setText("Your Username:");
            txtUusername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUusernameFocusLost

    private void txtUcompanynameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUcompanynameFocusGained
        if (txtUcompanyname.getText().equals("New company name: "))
        {
            txtUcompanyname.setText("");
            txtUcompanyname.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUcompanynameFocusGained

    private void txtUcompanynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUcompanynameFocusLost
        if (txtUcompanyname.getText().equals(""))
        {
            txtUcompanyname.setText("New company name: ");
            txtUcompanyname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUcompanynameFocusLost

    private void txtUemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUemailFocusGained
        if (txtUemail.getText().equals("New email: "))
        {
            txtUemail.setText("");
            txtUemail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUemailFocusGained

    private void txtUemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUemailFocusLost
        if (txtUemail.getText().equals(""))
        {
            txtUemail.setText("New email: ");
            txtUemail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUemailFocusLost

    private void txtUphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUphoneFocusGained
        if (txtUphone.getText().equals("New phone number: "))
        {
            txtUphone.setText("");
            txtUphone.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUphoneFocusGained

    private void txtUphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUphoneFocusLost
        if (txtUphone.getText().equals(""))
        {
            txtUphone.setText("New phone number: ");
            txtUphone.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUphoneFocusLost

    private void txtUpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpasswordFocusGained
        if (txtUpassword.getText().equals("New password: "))
        {
            txtUpassword.setText("");
            txtUpassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUpasswordFocusGained

    private void txtUpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpasswordFocusLost
        if (txtUpassword.getText().equals(""))
        {
            txtUpassword.setText("New password: ");
            txtUpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUpasswordFocusLost

    private void btnSviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSviewActionPerformed
        String username = txtSupid.getText(); // Get the username from the txtSupid field
        SupGetOwnInfoDatabase database = new SupGetOwnInfoDatabase();
        List<SupOwnDataModel> supplierList = database.getSupplierData(username);

        if (!supplierList.isEmpty()) {
            // Display supplier data in the profiletable
            dtm = (DefaultTableModel) profiletable.getModel();
            dtm.setRowCount(0);

            for (SupOwnDataModel supplier : supplierList) {
                String companyName = supplier.getCompanyname();
                String email = supplier.getEmail();
                String phone = supplier.getPhone();
                String password = supplier.getPassword();

                Object[] rowData = {username, companyName, email, phone, password};
                dtm.addRow(rowData);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No supplier data found for the given username.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSviewActionPerformed

    private void txtSupidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupidFocusGained
        if (txtSupid.getText().equals("Username: "))
        {
            txtSupid.setText("");
            txtSupid.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSupidFocusGained

    private void txtSupidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupidFocusLost
        if (txtSupid.getText().equals(""))
        {
            txtSupid.setText("Username: ");
            txtSupid.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSupidFocusLost

    private void btnSelfUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelfUpdateActionPerformed
        if ( concall == null ){
            concall = new SupUpdateSelfController(this);
        }
    }//GEN-LAST:event_btnSelfUpdateActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        if ( initCont == null){
            initCont = new SupUpdateProductController(this);
        }
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void txtPidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPidFocusGained
       if (txtPid.getText().equals("Product ID: "))
        {
            txtPid.setText("");
            txtPid.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtPidFocusGained

    private void txtPidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPidFocusLost
        if (txtPid.getText().equals(""))
        {
            txtPid.setText("Product ID: ");
            txtPid.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtPidFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Timer timer = new Timer(3000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            openUpdateFrame();
        }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("::: PRODUCT DATA... :::");
        MessageFormat footer = new MessageFormat("Nexlogix, A Powerful Supply Chain Management System");
        try{
            producttable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        }
        catch (PrinterException e){
            JOptionPane.showMessageDialog(null,"Error! Cannot Print"+e.getMessage());
            
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    // Add ActionListener
    public void addProductListener(ActionListener log)
    {
        btnaddProduct.removeActionListener(log); 
        btnaddProduct.addActionListener(log);
    }
    
    public void addUpdateListener(ActionListener log)
    {
        btnSelfUpdate.removeActionListener(log); 
        btnSelfUpdate.addActionListener(log);
    }

    public void addButtonListener(ActionListener listener) {
        btnDeleteProduct.addActionListener(listener);
    }
    
    public void addUpdateButtonListener(ActionListener update){
        btnUpdateProduct.addActionListener(update);
    }
    
    public void addDeleteButtonListener(ActionListener delete){
        btnDeleteProfile.addActionListener(delete);
    }

    // sending Button value
    public JButton getBtnDeleteProduct() {
        return btnDeleteProduct;
    }
    
    public JButton getBtnDeleteProfile(){
        return btnDeleteProfile;
    }

    public JTable getProductTable() {
        return producttable;
    }
    
    public JTable getProfileTable(){
        return profiletable;
    }
        
    // message fuction
    public void displayErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void displaySuccessMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new supplierDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnDeleteProfile;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProductView;
    private javax.swing.JButton btnSelfUpdate;
    private javax.swing.JButton btnSview;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JButton btnaddProduct;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnorderview;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable producttable;
    private javax.swing.JTable profiletable;
    private javax.swing.JTable sOrdertable;
    private javax.swing.JTextField txtCheck;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtSupid;
    private javax.swing.JTextField txtUcompanyname;
    private javax.swing.JTextField txtUemail;
    private javax.swing.JTextField txtUpassword;
    private javax.swing.JTextField txtUphone;
    private javax.swing.JTextField txtUusername;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtproductprice;
    private javax.swing.JTextField txtsuppliername;
    // End of variables declaration//GEN-END:variables

    public void clearField(){
        txtUusername.setText("");
        txtUcompanyname.setText("");
        txtUemail.setText("");
        txtUphone.setText("");
        txtUpassword.setText("");
    }
    
    public void clearAddField (){
        txtproductname.setText("");
        txtproductprice.setText("");
        txtsuppliername.setText("");
    }
    public void clearFields3(){
        txtPid.setText("");
        txtproductname.setText("");
        txtproductprice.setText("");
    }
    public void clearFields2(){
        txtCheck.setText("");
    }
    
    public void closeDash(){
        this.dispose();
    }
    
    private void openUpdateFrame() {
        frame = new SupdateFrame();
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                frame.dispose(); // Only close the update frame
            }
        });
        frame.setVisible(true);
    }
    
    

}
